⭐ Make this usable by any account/db

diff --git a/platter_watch b/platter_watch
--- a/platter_watch
+++ b/platter_watch
@@ -1,10 +1,22 @@
 #! /usr/bin/env bash
 
-echo "Creating initial Platter db config"
-python testsite/update_db.py testsite $(cat .git/HEAD | sed -e "s:^.*/::")
+if [ $# -eq 0 ]; then
+  echo "Please supply a Platter database instance name that your user has access to."
+  echo "usage: ./$0 <instance_name>"
+  exit 1
+fi
+
+echo "Creating initial Platter db config for instance $1"
+python testsite/update_db.py "$1" "$(cat .git/HEAD | sed -e "s:^.*/::")"
+
+if [ $? -ne 0 ]; then
+  echo "Error: please supply a Platter database instance that your user has access to."
+  exit 1
+fi
+
 echo "Watching for git branch changes..."
 watchmedo shell-command \
   --patterns=".git/HEAD" \
   --ignore-directories \
-  --command='[ ${watch_event_type} == "moved" ] && python testsite/update_db.py testsite $(cat .git/HEAD | sed -e "s:^.*/::")' \
+  --command='[ ${watch_event_type} == "moved" ] && python testsite/update_db.py '"$1"' $(cat .git/HEAD | sed -e "s:^.*/::")' \
   . 2> /dev/null
